### PR TITLE
Improve I18N Issues (Based on 3.7)

### PR DESCRIPTION
**Pull request by alexclassroom**
Make all UI strings localizable.

### CODE REVIEW

**Comment by alexclassroom** [comment]
- This plugin's **"Requires at least"** is below 4.6. so you need to set a Text Domain in **membed-calendly-scheduling.php**, and it needs to be `embed-calendly-scheduling` to correctly internationalize this plugin! Please refer to [this article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains).
 - **"Requires at least"** (4.0) is below 4.6 so a `load_plugin_textdomain` is **needed**, please refer to this [official article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain).

**Comment by thatshycoder** [comment]
Hi @alexclassroom thanks for taking the time to fix this! I'll review the PR and let you know when it's deployed to WordPress.

**Comment by thatshycoder** [comment]
> * This plugin's **"Requires at least"** is below 4.6. so you need to set a Text Domain in **membed-calendly-scheduling.php**, and it needs to be `embed-calendly-scheduling` to correctly internationalize this plugin! Please refer to [this official article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains).
> * **"Requires at least"** (4.0) is below 4.6 so a `load_plugin_textdomain` is **needed**, please refer to [this official article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain).
> * Please also take care of these two above issues.



> * This plugin's **"Requires at least"** is below 4.6. so you need to set a Text Domain in **membed-calendly-scheduling.php**, and it needs to be `embed-calendly-scheduling` to correctly internationalize this plugin! Please refer to [this official article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains).
> * **"Requires at least"** (4.0) is below 4.6 so a `load_plugin_textdomain` is **needed**, please refer to [this official article](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain).
> * Please also take care of these two above issues.

Thanks for pointing this out

**Comment by alexclassroom** [comment]
Any update?

**Pull request closed without merging**
